// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvM869VfM2bDvgSRoVqmFeDXHWw28bAn8',
    appId: '1:283991589356:web:48eced93752f4669d5c0c9',
    messagingSenderId: '283991589356',
    projectId: 'flutter-login-app-96193',
    authDomain: 'flutter-login-app-96193.firebaseapp.com',
    storageBucket: 'flutter-login-app-96193.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM4uQpp3lKH7h1s24UON4SnZiO7KdEXvs',
    appId: '1:283991589356:android:449485de3224172dd5c0c9',
    messagingSenderId: '283991589356',
    projectId: 'flutter-login-app-96193',
    storageBucket: 'flutter-login-app-96193.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg7cTt65y1tG5An0pfRDX38t_32EF50BY',
    appId: '1:283991589356:ios:5b7e6269b856be86d5c0c9',
    messagingSenderId: '283991589356',
    projectId: 'flutter-login-app-96193',
    storageBucket: 'flutter-login-app-96193.appspot.com',
    iosBundleId: 'com.example.authbased',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg7cTt65y1tG5An0pfRDX38t_32EF50BY',
    appId: '1:283991589356:ios:5e9882e2982e36b4d5c0c9',
    messagingSenderId: '283991589356',
    projectId: 'flutter-login-app-96193',
    storageBucket: 'flutter-login-app-96193.appspot.com',
    iosBundleId: 'com.example.authbased.RunnerTests',
  );
}
